export const OPENSTREETMAP_URL = process.env.NEXT_PUBLIC_OPENSTREETMAP_URL || ''
export const SOCKET_URL = process.env.NEXT_PUBLIC_SOCKET_URL || ''

const API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY || ''
const AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || ''
const PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || ''
const STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || ''
const MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || ''
const APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID || ''
const MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || ''

export {
  API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
  APP_ID,
  MEASUREMENT_ID
}
